import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import DocLayout, { DocSection } from "@/components/DocLayout";

export const metadata = {
  title: "Terms of Service — Scrivly",
  description: "Read the terms and conditions for using Scrivly's AI-powered Etsy listing generator.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)]">
      <Navbar />

      <main>
        <DocLayout title="Terms of Service" lastUpdated="June 2026">
          <DocSection>
            <p>
              By using Scrivly you agree to these Terms of Service. Please read them carefully. If you do
              not agree, do not use the service.
            </p>
          </DocSection>

          <DocSection heading="1. The Service">
            <p>
              Scrivly is an AI-powered listing generation tool for Etsy sellers. We provide a credit-based
              service where users purchase credits to generate SEO-optimized Etsy listings from product
              photos.
            </p>
            <p>Scrivly is operated by Aman Ali, Sialkot, Pakistan.</p>
          </DocSection>

          <DocSection heading="2. Accounts">
            <p>
              You must provide a valid email address to create an account. You are responsible for
              maintaining the security of your account password. You must not share your account with
              others. You must be at least 13 years old to use Scrivly.
            </p>
          </DocSection>

          <DocSection heading="3. Credits and Payments">
            <p>
              Credits are purchased through our Etsy shop as digital products. Credits are non-refundable
              once redeemed to your account. Credits never expire. Each unique redeem code is single-use
              and tied to one account. Sharing or reselling redeem codes is not permitted and will result
              in account suspension.
            </p>
            <p>
              Each generation (photo to listing) costs 6 credits, or 10 credits with price research
              included. Credit costs for other features are displayed in the dashboard before use.
            </p>
          </DocSection>

          <DocSection heading="4. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>Use Scrivly to generate content that violates Etsy&apos;s policies</li>
              <li>Attempt to reverse engineer or copy the service</li>
              <li>Create multiple accounts to abuse the credit system</li>
              <li>Use automated scripts or bots to access the service</li>
              <li>Share, resell, or redistribute generated content as a competing service</li>
            </ul>
            <p>Violation of these terms will result in immediate account suspension without refund.</p>
          </DocSection>

          <DocSection heading="5. AI-Generated Content">
            <p>
              Content generated by Scrivly is produced by AI (Anthropic Claude). We do not guarantee the
              accuracy, completeness, or fitness for purpose of generated listings. You are responsible for
              reviewing all generated content before publishing to Etsy. Generated content may be similar
              to content generated for other users using similar products.
            </p>
          </DocSection>

          <DocSection heading="6. Etsy Integration">
            <p>
              When you connect your Etsy shop to Scrivly, you grant us permission to create draft listings
              in your shop on your behalf. We do not publish listings without your review and approval. We
              do not access or modify any other aspect of your Etsy shop.
            </p>
          </DocSection>

          <DocSection heading="7. Intellectual Property">
            <p>
              Scrivly and its original content, features, and functionality are owned by Scrivly and
              protected by intellectual property laws. Content you generate using Scrivly belongs to you.
            </p>
          </DocSection>

          <DocSection heading="8. Disclaimer of Warranties">
            <p>
              Scrivly is provided as-is without warranties of any kind. We do not guarantee that the
              service will be uninterrupted, error-free, or that generated listings will achieve specific
              SEO rankings or sales results.
            </p>
          </DocSection>

          <DocSection heading="9. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, Scrivly shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the service.
            </p>
          </DocSection>

          <DocSection heading="10. Changes to Terms">
            <p>
              We reserve the right to modify these terms at any time. Continued use of Scrivly after
              changes constitutes acceptance of the new terms.
            </p>
          </DocSection>

          <DocSection heading="11. Contact">
            <p>
              Questions about these Terms? Email{" "}
              <a href="mailto:scrivly@gmail.com" className="text-brand-pink hover:underline">
                scrivly@gmail.com
              </a>{" "}
              or message us at{" "}
              <a
                href="https://www.etsy.com/shop/AmanCraftio"
                target="_blank"
                rel="noopener noreferrer"
                className="text-brand-pink hover:underline"
              >
                etsy.com/shop/AmanCraftio
              </a>
              .
            </p>
          </DocSection>
        </DocLayout>
      </main>

      <Footer />
    </div>
  );
}
