-- Referral system — run this once in the Supabase SQL Editor.
--
-- Note: this repo's existing `handle_new_user()` trigger (the one that
-- creates a profiles row on signup) lives only in the Supabase project,
-- not in this migrations folder, so its body is unknown here. Rather than
-- guessing and overwriting it, referral_code is generated by a separate
-- BEFORE INSERT trigger on profiles — it fires regardless of how the row
-- gets inserted, so it works whether or not handle_new_user already sets
-- other columns.

-- 1. Referral columns on profiles
alter table profiles
  add column if not exists referral_code text unique,
  add column if not exists referred_by uuid references profiles(id),
  add column if not exists referral_credits_earned integer not null default 0,
  add column if not exists total_referrals integer not null default 0,
  add column if not exists referral_purchases integer not null default 0;

-- 2. Referral events log — one row per signup/purchase reward
create table if not exists referral_events (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid references profiles(id) on delete cascade,
  referred_id uuid references profiles(id) on delete cascade,
  event_type text not null, -- 'signup' or 'purchase'
  credits_awarded integer not null default 0,
  created_at timestamptz not null default now()
);

alter table referral_events enable row level security;

drop policy if exists "Users see own referral events" on referral_events;
create policy "Users see own referral events"
  on referral_events for select
  using (auth.uid() = referrer_id);

-- 3. Auto-generate a unique 8-character referral code for every profile
create or replace function set_referral_code()
returns trigger as $$
declare
  code text;
  exists_check integer;
begin
  if new.referral_code is not null then
    return new;
  end if;

  loop
    code := upper(substring(replace(replace(encode(gen_random_bytes(6), 'base64'), '+', ''), '/', ''), 1, 8));
    select count(*) into exists_check from profiles where referral_code = code;
    exit when exists_check = 0;
  end loop;

  new.referral_code := code;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_set_referral_code on profiles;
create trigger trg_set_referral_code
  before insert on profiles
  for each row
  execute function set_referral_code();

-- 4. Backfill referral codes for profiles that already exist
do $$
declare
  row_id uuid;
  code text;
  exists_check integer;
begin
  for row_id in select id from profiles where referral_code is null loop
    loop
      code := upper(substring(replace(replace(encode(gen_random_bytes(6), 'base64'), '+', ''), '/', ''), 1, 8));
      select count(*) into exists_check from profiles where referral_code = code;
      exit when exists_check = 0;
    end loop;
    update profiles set referral_code = code where id = row_id;
  end loop;
end $$;
